### ISSUE TITLE
Project description

### ISSUE THREAD

**Issue by ADWrobo** [ADWrobo/coffee-ranking-platform#1]
# Project requirements for this phase:

## Group Project

This is the first part of the group assignment.  This week, you will be working with your group members to decide what kind of site to build along with some initial designs (more on that below).  You can build any kind of website you want, for example a mock restaurant menu/order site or a shopping site.  You can use the materials covered in class along with any other CSS frameworks that you might have learned on your own. For the API service, plan on using ExpressJS (I will cover it in class on 4/3).  For now assume that any data needed for your website will be provided by the API service.

## Grading Criteria for the entire project

    Does the site do what the initial submission summary says?
    Does the site resemble the wireframes handed in?
    Are the styles written cleanly and non-redundant?
    Does the JavaScript work properly and without errors?
    Does the API service retrieve/modify data as necessary? (API will be covered in 4/3 lecture)

Once you have decided on what kind of site you will be building, you will be creating some wireframes. If you are not experienced with wireframes, please read the article at https://blog.hubspot.com/website/website-wireframe - There are many free wireframing tools available, you may use anything you wish; one of the free ones is https://app.diagrams.net/ ; you can save your work to Google drive or other cloud providers using this tool.

## Submission for 4/3:

I need one person from the group to email me one pdf file which contains the following:

    A brief summary of what your website is going to be (Use as much words as you need to clearly explain your idea).
    Wireframe of the your site.
    Make sure to include all the group member names on the 1st page of the pdf file.
    Make sure to include "SEIS-622" in the subject.

**Comment by ADWrobo** [comment]
# Description 
_Currently WIP_

An app to rate individual coffee drinks at coffee shops that you visit, rather than rating the coffee shop itself.

## Potential Features

    Ability to add your drink, coffee location, rating and comment
        Perhaps we could use Google API to find & add Coffee shop (or just have fake data)
        If time allows, we could add option to upload a picture
    Edit Ratings added
    Delete Ratings added
    Stretch Goals
        Search for ratings based on location, coffee shop, types of coffee, etc.
        Create User Profiles
            Ability to search for your own ratings added
            Limit edits & deletes to your own ratings

**Comment by BetsyRowley** [comment]
Link to document with project summary: https://uofstthomasmn-my.sharepoint.com/:w:/r/personal/allh2951_stthomas_edu/Documents/622%20Group%20Project/Group%20Project%20Part%201.docx?d=w67863679bab64e8ba5e7389082859df2&csf=1&web=1&e=yjXULV
